# Generated by Django 5.2.1 on 2025-05-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.CharField(default='', max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('numfile', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.CharField(default='', max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('userName', models.CharField(default='myname', max_length=100)),
                ('accessNames', models.JSONField(default=list)),
                ('isFavorite', models.BooleanField(default=False)),
                ('numfile', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
                ('mac', models.IntegerField(default=-1)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
