# Generated by Django 5.2.1 on 2025-05-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
