<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_image_accessnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
=======
# Generated by Django 5.2.1 on 2025-05-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_image_accessnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
>>>>>>> 494cc95ff01940e6a9be0350084b1fd140572d7d
