<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
=======
# Generated by Django 5.2.1 on 2025-05-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
>>>>>>> 494cc95ff01940e6a9be0350084b1fd140572d7d
