<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_image_isfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
=======
# Generated by Django 5.2.1 on 2025-05-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_image_isfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
>>>>>>> 494cc95ff01940e6a9be0350084b1fd140572d7d
